#!/bin/sh
# Bundles the app's pure alert code for the send-alerts Edge Function (Deno). Run after changing anything
# under src/lib/domain, src/lib/alerts-job, src/lib/dates or src/components/format.ts; a test fails when
# the committed bundle is stale.
set -e
out="${1:-supabase/functions/send-alerts/shared.bundle.js}"
tmp="$(mktemp)"
deno bundle --quiet --config scripts/alerts-bundle.deno.json --unstable-sloppy-imports -o "$tmp" scripts/alerts-bundle-entry.ts
{ echo "// Generated by pnpm bundle:alerts from scripts/alerts-bundle-entry.ts. Do not edit."; cat "$tmp"; } > "$out"
rm -f "$tmp"
